### PR TITLE
Ported unQuery to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by ffMathy**
This ports unQuery to .NET Standard 2.0, meaning that support is added for the following frameworks:
- .NET Framework 4.6.1
- .NET Core 2.0
- Mono 5.4
- Xamarin.iOS 10.14
- Xamarin.Mac 3.8
- Xamarin.Android 7.5

Also:
- Used `nameof` in places where appropriate.
- Removed unused usings.
- Updated to latest NUnit version.

**Warning:** I have not yet run all DB-related tests - I was hoping you could help me get that working one day - do I just set up a new DB called `unQuery`, and it'll work, or do I need some special setup? 

All non-DB related tests are passing.

### CODE REVIEW

**Comment by improvedk** [comment]
@ffMathy So we finally got round to getting this merged. We'll do a merge to a temp branch, as Carsten has made a small couple of fixes & run all tests separately. He'll branch from the temp branch, once your PR is approved.

Can I persuade you to fix the final conflict here, so I can approve the PR? :)

**Comment by ffMathy** [comment]
Exciting stuff, and congrats on the journey to .NET Standard and Core! 👍 🙇 

I'll see if I can get some time in the upcoming week!

Alternatively, you can fork my own fork of unQuery (from my repo here: https://github.com/ffMathy/unQuery), make a PR targeting this repo, and resolve the conflicts yourselves (if you can't wait).

Cheers.

**Comment by improvedk** [comment]
PR merged in via Carstens followup-PR - thanks! :)

**Comment by ffMathy** [comment]
Glad you got it worked out!

**Pull request closed without merging**
